services:
  app:
    build:
      context: .
    environment:
      - VIRTUAL_HOST=node-app.local
      - VIRTUAL_PORT=5000
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /code
    networks:
      - proxy-tier
      - app-network

  redis:
    image: "redis:alpine"
    networks:
      - app-network

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

networks:
  app-network:
  proxy-tier:
